# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DemoCalc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys

import Mouse
import SimpleOcr
from SimpleForm import Form, Control
from PyQt5.QtWidgets import QMainWindow, QApplication
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DemoCalc(object):
    is_1st = True
    store = 0
    operator = ''
    def setupUi(self, DemoCalc):
        DemoCalc.setObjectName("DemoCalc")
        DemoCalc.resize(450, 220)
        self.btnE = QtWidgets.QPushButton(DemoCalc)
        self.btnE.setGeometry(QtCore.QRect(10, 170, 31, 31))
        self.btnE.setObjectName("btn0")
        self.btn0 = QtWidgets.QPushButton(DemoCalc)
        self.btn0.setGeometry(QtCore.QRect(50, 170, 31, 31))
        self.btn0.setObjectName("btn0")
        self.btn1 = QtWidgets.QPushButton(DemoCalc)
        self.btn1.setGeometry(QtCore.QRect(10, 130, 31, 31))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(DemoCalc)
        self.btn2.setGeometry(QtCore.QRect(50, 130, 31, 31))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(DemoCalc)
        self.btn3.setGeometry(QtCore.QRect(90, 130, 31, 31))
        self.btn3.setObjectName("btn3")
        self.btn4 = QtWidgets.QPushButton(DemoCalc)
        self.btn4.setGeometry(QtCore.QRect(10, 90, 31, 31))
        self.btn4.setObjectName("btn4")
        self.btn5 = QtWidgets.QPushButton(DemoCalc)
        self.btn5.setGeometry(QtCore.QRect(50, 90, 31, 31))
        self.btn5.setObjectName("btn5")
        self.btn8 = QtWidgets.QPushButton(DemoCalc)
        self.btn8.setGeometry(QtCore.QRect(50, 50, 31, 31))
        self.btn8.setObjectName("btn8")
        self.btn6 = QtWidgets.QPushButton(DemoCalc)
        self.btn6.setGeometry(QtCore.QRect(90, 90, 31, 31))
        self.btn6.setObjectName("btn6")
        self.btn7 = QtWidgets.QPushButton(DemoCalc)
        self.btn7.setGeometry(QtCore.QRect(10, 50, 31, 31))
        self.btn7.setObjectName("btn7")
        self.btn9 = QtWidgets.QPushButton(DemoCalc)
        self.btn9.setGeometry(QtCore.QRect(90, 50, 31, 31))
        self.btn9.setObjectName("btn9")
        self.btn_sub = QtWidgets.QPushButton(DemoCalc)
        self.btn_sub.setGeometry(QtCore.QRect(130, 90, 31, 31))
        self.btn_sub.setObjectName("btn_sub")
        self.btn_add = QtWidgets.QPushButton(DemoCalc)
        self.btn_add.setGeometry(QtCore.QRect(130, 50, 31, 31))
        self.btn_add.setObjectName("btn_add")
        self.btn_divide = QtWidgets.QPushButton(DemoCalc)
        self.btn_divide.setGeometry(QtCore.QRect(130, 170, 31, 31))
        self.btn_divide.setObjectName("btn_divide")
        self.btn_mult = QtWidgets.QPushButton(DemoCalc)
        self.btn_mult.setGeometry(QtCore.QRect(130, 130, 31, 31))
        self.btn_mult.setObjectName("btn_mult")
        self.btn_decimal = QtWidgets.QPushButton(DemoCalc)
        self.btn_decimal.setGeometry(QtCore.QRect(90, 170, 31, 31))
        self.btn_decimal.setObjectName("btn_decimal")
        self.tb_total = QtWidgets.QLabel(DemoCalc)
        self.tb_total.setGeometry(QtCore.QRect(10, 10, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tb_total.setFont(font)
        self.tb_total.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.tb_total.setObjectName("tb_total")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(DemoCalc)
        self.plainTextEdit.setGeometry(QtCore.QRect(170, 50, 270, 70))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(DemoCalc)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(170, 130, 270, 70))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")

        self.btn0.clicked.connect(self.btn0_click)
        self.btn1.clicked.connect(self.btn1_click)
        self.btn2.clicked.connect(self.btn2_click)
        self.btn3.clicked.connect(self.btn3_click)
        self.btn4.clicked.connect(self.btn4_click)
        self.btn5.clicked.connect(self.btn5_click)
        self.btn6.clicked.connect(self.btn6_click)
        self.btn7.clicked.connect(self.btn7_click)
        self.btn8.clicked.connect(self.btn8_click)
        self.btn9.clicked.connect(self.btn9_click)
        self.btn_add.clicked.connect(self.btn_add_click)
        self.btn_sub.clicked.connect(self.btn_sub_click)
        self.btn_mult.clicked.connect(self.btn_mult_click)
        self.btn_divide.clicked.connect(self.btn_divide_click)
        self.btn_decimal.clicked.connect(self.btn_decimal_click)
        self.btnE.clicked.connect(self.btnE_click)

        self.retranslateUi(DemoCalc)
        QtCore.QMetaObject.connectSlotsByName(DemoCalc)
        DemoCalc.setTabOrder(self.btn0, self.btn1)
        DemoCalc.setTabOrder(self.btn1, self.btn2)
        DemoCalc.setTabOrder(self.btn2, self.btn4)
        DemoCalc.setTabOrder(self.btn4, self.btn5)
        DemoCalc.setTabOrder(self.btn5, self.btn3)
        DemoCalc.setTabOrder(self.btn3, self.btn6)
        DemoCalc.setTabOrder(self.btn6, self.btn7)
        DemoCalc.setTabOrder(self.btn7, self.btn8)
        DemoCalc.setTabOrder(self.btn8, self.btn9)
        DemoCalc.setTabOrder(self.btn9, self.btn_decimal)
        DemoCalc.setTabOrder(self.btn_decimal, self.btn_add)
        DemoCalc.setTabOrder(self.btn_add, self.btn_sub)
        DemoCalc.setTabOrder(self.btn_sub, self.btn_mult)
        DemoCalc.setTabOrder(self.btn_mult, self.btn_divide)
        DemoCalc.setTabOrder(self.btn_divide, self.plainTextEdit)
        DemoCalc.setTabOrder(self.plainTextEdit, self.plainTextEdit_2)

    def btn0_click(self):
        self.append('0')

    def btn1_click(self):
        self.append('1')

    def btn2_click(self):
        self.append('2')

    def btn3_click(self):
        self.append('3')

    def btn4_click(self):
        self.append('4')

    def btn5_click(self):
        self.append('5')

    def btn6_click(self):
        self.append('6')

    def btn7_click(self):
        self.append('7')

    def btn8_click(self):
        self.append('8')

    def btn9_click(self):
        self.append('9')

    def btn_add_click(self):
        self.append('+')

    def btn_sub_click(self):
        self.append('-')

    def btn_mult_click(self):
        self.append('*')

    def btn_divide_click(self):
        self.append('/')

    def btn_decimal_click(self):
        self.append('.')

    def btnE_click(self):
        self.append('=')

    def append(self, nbr):
        if nbr != '+' and nbr != '-' and nbr != '*' and nbr != '/' and nbr != '=':
            txt = self.tb_total.text() + nbr
            if '.' in txt:
                n = float(txt)
            else:
                n = int(txt)
            if nbr == '.':
                n = txt
            self.tb_total.setText(str(n))
        elif nbr == '=':
            if self.operator == '+':
                self.store += float(self.tb_total.text())
            elif self.operator == '-':
                self.store -= float(self.tb_total.text())
            elif self.operator == '*':
                self.store *= float(self.tb_total.text())
            elif self.operator == '/':
                self.store /= float(self.tb_total.text())
            txt = str(self.store)
            if txt.endswith('.0'):
                lng = len(txt)
                txt = txt[0:lng-2]
            self.tb_total.setText(txt)
            self.operator = ''
        else:
            if self.is_1st:
                self.store += float(self.tb_total.text())
            self.operator = nbr
            txt = str(self.store)
            if txt.endswith('.0'):
                lng = len(txt)
                txt = txt[0:lng-2]
            self.tb_total.setText('0')
            self.is_1st = False

    def retranslateUi(self, DemoCalc):
        _translate = QtCore.QCoreApplication.translate
        DemoCalc.setWindowTitle(_translate("DemoCalc", "Demo Form"))
        self.btnE.setText(_translate("DemoCalc", "="))
        self.btn0.setText(_translate("DemoCalc", "0"))
        self.btn1.setText(_translate("DemoCalc", "1"))
        self.btn2.setText(_translate("DemoCalc", "2"))
        self.btn3.setText(_translate("DemoCalc", "3"))
        self.btn4.setText(_translate("DemoCalc", "4"))
        self.btn5.setText(_translate("DemoCalc", "5"))
        self.btn6.setText(_translate("DemoCalc", "6"))
        self.btn7.setText(_translate("DemoCalc", "7"))
        self.btn8.setText(_translate("DemoCalc", "8"))
        self.btn9.setText(_translate("DemoCalc", "9"))
        self.btn_sub.setText(_translate("DemoCalc", "-"))
        self.btn_add.setText(_translate("DemoCalc", "+"))
        self.btn_divide.setText(_translate("DemoCalc", "/"))
        self.btn_mult.setText(_translate("DemoCalc", "*"))
        self.btn_decimal.setText(_translate("DemoCalc", "."))
        self.tb_total.setText(_translate("DemoCalc", "0"))
        self.plainTextEdit.setPlainText(_translate("DemoCalc", "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Curabitur tristique dapibus sodales."))

class MainWindow(QMainWindow, Ui_DemoCalc):

    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.setupUi(self)

if __name__ == '__main__':
    #Mouse.move((32, 372))
    #Mouse.move((505, 780))

    SimpleOcr.add_font('/home/michaelhalpin/Desktop/Default')
    #text = SimpleOcr.perform_ocr('Default', (10, 400, 100, 18), .99, 128, 4)
    text = SimpleOcr.perform_ocr('Default', (10, 385, 1290, 100), 0.99, 128, px_space=3)

    quit()

    try:
        app = QApplication(sys.argv)
        ex = MainWindow()
        ex.show()

        calc = Form("test")
        calc.controls.append(Control('2', ''))

        sys.exit(app.exec_())

    except:
        e_type, e_value, e_trace = sys.exc_info()
        print(str(e_type) + '\n' + str(e_value) + '\n' + str(e_trace))